### ISSUE TITLE
"IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer"

### ISSUE THREAD

**Issue by mjoehler94** [domvwt/pandas-downcast#10]
Opening a new issue to reference the previous issue (#9 ) which was closed but not solved. I've included a minimum reproducible example in the previous issue.

**Comment by domvwt** [comment]
Hi @mjoehler94, thanks for reopening this and providing a reproducible example. I'll work on a fix over the next few days, apologies for the delay.

**Comment by domvwt** [comment]
I've uploaded a new version to PyPI with the fix implemented. Thanks again for your help.
