### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float128'

### ISSUE THREAD

**Issue by kevin-goetz** [domvwt/pandas-downcast#4]
Hi Dom,
great module! Had the same idea but you were faster :-)
When importing pdcast there is an error though: AttributeError: module 'numpy' has no attribute 'float128'
I changed your types.py and deleted the np.float128-entry of your FLOAT_TYPES list - tested it and works just fine.

pdcast version: 1.0.0
numpy version: 1.21.0
pandas version: 1.2.5

![grafik](https://user-images.githubusercontent.com/80414465/123410054-2879dc00-d5af-11eb-8042-56a57fd2b85c.png)

greets,
Kevin

**Comment by domvwt** [comment]
Hi Kevin,

Glad you found the package useful!

Thanks for pointing out this error - looks like it's platform specific so missed it with my linux only test suite. In any case, it doesn't seem like the float128 type is very reliable judging by this conversation [on stackoverflow](https://stackoverflow.com/questions/9062562/what-is-the-internal-precision-of-numpy-float128). I've now removed it from the possible float types as you suggested.

Cheers,
Dom
