### ISSUE TITLE
How to deal with "IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer"

### ISSUE THREAD

**Issue by castorfou** [domvwt/pandas-downcast#9]
Just calling pdc.downcast on a dataframe, I get the following exception:

`IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer`
In this dataframe I have lots of float64 columns with NaN.

What is the proper way to deal with that? Can pdc.downcast handle NaN in a way?

**Comment by domvwt** [comment]
Hi @castorfou, thanks for reporting this issue.

Could you share a minimal example that replicates this behaviour, please? I suspect that you may need to infer the schema and then coerce the DataFrame like this:

```python
# Infer minimum schema for DataFrame.
schema = pdc.infer_schema(df)

# Coerce DataFrame to schema - required if converting float to Pandas Integer.
df_new = pdc.coerce_df(df, schema)
```

It might make sense to perform this coercion automatically within the `downcast` function - feel free to fork the repo and raise a pull request if you'd be happy to implement the necessary changes!

**Comment by domvwt** [comment]
I'm going to close this issue as stale - feel free to reopen if you can provide a minimal example to reproduce the error

**Comment by mjoehler94** [comment]
I get the same issue as well. Here is a reproducible example using the flights.csv dataset from kaggle (https://www.kaggle.com/datasets/usdot/flight-delays?resource=download&select=flights.csv) which in it's raw form is about 1.3 GB.

```python
df = pd.read_csv("../path/to/flights.csv", low_memory=False)

df_downcast = pdc.downcast(df)

# Results in:
# IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer 

```

The same error persists when trying to infer the schema first:
```python
df = pd.read_csv("../path/to/flights.csv", low_memory=False)

# Infer minimum schema for DataFrame.
schema = pdc.infer_schema(df)

# Coerce DataFrame to schema - required if converting float to Pandas Integer.
df_new = pdc.coerce_df(df, schema)

# Still results in:
# IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer 

```
